---
title: "Same Comapany Internship to Employment"
author: "Thompson"
date: "April 4, 2018"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DBI)
library(lubridate)
library(scales)
source("conn.R")
```

```{r}
?left_join()

graduation <- tbl(conStudent, 'graduation') %>% collect()
internship <- tbl(conStudent, 'internship') %>% collect()
organization <- tbl(conStudent, 'organization') %>% collect()
currPosition <- tbl(conStudent, 'currentPosition') %>% collect()
fulltime <- tbl(conStudent, 'fulltime') %>% collect()

xx<- internship %>% 
  left_join(organization) %>% 
  group_by(organizationId) %>% 
  filter(!is.na(organizationId)) #%>%    #to drop the NA, use filter with a negate operator

OrgtoInt <- right_join(organization, internship, by = "organizationId") 

#this shows the link between graduates who had internships to their currentposition (so if they stayed with same company)
CurrtoInt <- left_join(currPosition, internship, by = "graduationId")
  
#then, this shows if the current position at same company is full time ^^
fTime<- left_join(fulltime, CurrtoInt, by = "idCurrentPosition") %>% collect()

#now, need to drop other info and filter for how many students took this route 


fTime %>% group_by()

#0.
percInterns <- length(internship$internshipId)/length(graduation$graduationId) #need to get as a percent format


#1. 
percStay <- length(fTime$idCurrentPosition)/length(internship$internshipId) 

#2. 
percChange <- #come back
  
#3.
percNoneorNA <- #


#stats: 1. if the student had internship --> fulltime (total/internship total) expected med-high
      # 2. if the student had internship --> diff company? (total/internship total) expected med-high
      # 3. if the student did not get hired --> no current position (total/internship total) expected low
      # 0. how many students had an internship --> (internship total; internship total/graduateid total)

```
Of all of the LSU graduate from 2017, `'r percInterns`% had internships during their undegrad. 

Of those who had internships, `r percStay`% are not in full time positions with that company. 

Of 
